# fly.toml app configuration file generated for questlist on 2024-09-12T12:39:11+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'questlist'
primary_region = 'sin'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
[deploy]
  release_command = "./bin/rails db:prepare"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

