default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: root
  password: 12341234
  host: localhost

development:
  <<: *default
  database: todo

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: my_app_production
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

